build(building-blocks): fix failed step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -11,9 +11,11 @@ jobs:
    echo-goodbye:
       runs-on: ubuntu-latest
       steps:
-         - name: Failed step
-           run: |
-             echo "This step has failed"
-             exit 1
+         # - name: Failed step
+         #   run: |
+         #     echo "This step has failed"
+         #     exit 1
+         - name: Successfull step
+           run: echo "This step runs successfully"
          - name: Say goodbye
            run: echo "Goodbye world!"
